version: 1

merge:
  trigger:
    labels: ["merge when ready"]
    comment_substrings: ["==MERGE_WHEN_READY=="]
  ignore:
    labels: ["do not merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: rebase
  delete_after_merge: false
  allow_merge_with_no_checks: false

update:
  trigger:
    labels: ["wip", "update me"]

