name: build
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: depends
      run: sudo apt install libboost-filesystem-dev libboost-program-options-dev
    - name: build
      run: cmake -Bbuild && make -C build
    - uses: actions/upload-artifact@v1
      with:
        name: supersm-linux-amd64
        path: ./build/supersm

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: depends
      run: brew install boost
    - name: build
      run: cmake -Bbuild && make -C build
    - uses: actions/upload-artifact@v1
      with:
        name: supersm-macos
        path: ./build/supersm

  windows:
    runs-on: windows-latest
    steps:
    - uses: numworks/setup-msys2@v1
      with:
        update: true
    - name: depends
      run: |
        msys2do pacman --sync --noconfirm --needed mingw-w64-x86_64-boost mingw-w64-x86_64-make mingw64/mingw-w64-x86_64-gcc
    - uses: actions/checkout@v2
    - name: build
      working-directory: ./
      run: |
        Remove-Item Env:BOOST_ROOT
        $mingw64_ROOT = "D:/a/_temp/msys/msys64/mingw64"
        $env:PATH += ";$mingw64_ROOT"
        $env:PATH += ";$mingw64_ROOT/bin"
        $env:PATH += ";$mingw64_ROOT/include"
        $env:PATH = $env:PATH.Replace(';C:\hostedtoolcache\windows\Boost\1.72.0','')
        cmake -Bbuild -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_C_COMPILER="$mingw64_ROOT/bin/gcc.exe" -DCMAKE_CXX_COMPILER="$mingw64_ROOT/bin/g++.exe"
        mingw32-make -C build
    - uses: actions/upload-artifact@v1
      with:
        name: supersm-windows
        path: ./build/supersm.exe

