name: C/C++ CI

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: depends
      run: sudo apt install libboost-filesystem-dev libboost-program-options-dev
    - name: build
      run: cmake -Bbuild && make -C build
    - uses: actions/upload-artifact@v1
      with:
        name: supersm-linux-amd64
        path: ./build/supersm

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: depends
      run: brew install boost
    - name: build
      run: cmake -Bbuild && make -C build
    - uses: actions/upload-artifact@v1
      with:
        name: supersm-macos
        path: ./build/supersm

