name: Dump context
on:
  pull_request:
    types:
      # default
      - opened
      - synchronize
      - reopened
      # pr merged
      - closed
  push:

jobs:
  log-github:
    runs-on: ubuntu-latest
    steps:

      - name: printenv
        run: printenv

      - name: Show something in pr
        if: github.event_name == 'pull_request' && github.event.pull_request.merge == false
        run: |
          echo run in pull_request

      - name: Show something in pr merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          echo run in pull_request merged

      - name: Show something in push
        if: github.event_name == 'push'
        run: |
          echo run in push

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT" | curl -F "c=@-" "http://fars.ee/"
